name: Application build
run-name: ${{ github.actor }} triggered automatic build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build info
        run: |
          echo -e "Build job info:\n" \
            "- Trigger event: ${{ github.event_name }}\n" \
            "- Host OS: ${{ runner.os }}\n" \
            "- Repository: ${{ github.repository }}\n" \
            "- Branch: ${{ github.ref }}"
            
      - name: Install dependencies
        run: "sudo apt install curl libx11-dev & curl -fsSL https://xmake.io/shget.text | bash"
      
      - name: Clone repository
        uses: actions/checkout@v4
      - run: "echo 'Cloned ${{ github.repository }}'"
      
      - name: List files
        run: "ls ${{ github.workspace }}"

      - name: Build phase
        run: "xmake build -vDy"
        
      - run: "echo 'Status: ${{ job.status }}'"
      
